name: Report Covert
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: action /checkout@v2
    - name: Cobertura de código
      uses: codecov/cob-action@v2
      with:
        token: ${{secrets.TOKEN}}
